sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 3768491
  alioss:
    bucket-name: java-ai-20250619
    endpoint: oss-cn-beijing.aliyuncs.com

    access-key-id: ${ALI_ACCESS_KEY_ID}
    access-key-secret: ${ALI_ACCESS_KEY_SECRET}
  redis:
    host: localhost
    port: 6379
    password: 3768491
    database: 10
  wechat:
    appid: wxe679454e278f07ae
    secret: ebd720a0f50503333b7eecfac9d7834d